import React, { useState } from 'react';
import { CreditCard, Coins, Wallet, RefreshCw, AlertTriangle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { useAuth } from '@/contexts/AuthContext';
import ReturnForm from '@/components/pos/ReturnForm';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Tabs,
  TabsContent,
  TabsList,
  TabsTrigger,
} from "@/components/ui/tabs";
import { toast } from '@/hooks/use-toast';
import { Customer } from '@/contexts/CustomerContext';
import { useTransactions, SaleTransaction } from '@/contexts/TransactionContext';
import { useCustomers } from '@/contexts/CustomerContext';
import { useInventory } from '@/contexts/InventoryContext';

interface PaymentPanelProps {
  cartItems: {
    id: string;
    name: string;
    price: number;
    quantity: number;
    sku?: string;
    karat?: string;
    weight?: string;
    discount?: number;
  }[];
  customer: Customer | null;
  onPaymentComplete: () => void;
  onAdminAction: (action: 'delete' | 'return', transactionId?: string) => void;
}

const PaymentPanel: React.FC<PaymentPanelProps> = ({ 
  cartItems, 
  customer, 
  onPaymentComplete,
  onAdminAction
}) => {
  const [isPaymentDialogOpen, setIsPaymentDialogOpen] = useState(false);
  const [isAdminDialogOpen, setIsAdminDialogOpen] = useState(false);
  const [isReturnFormOpen, setIsReturnFormOpen] = useState(false);
  const [adminAction, setAdminAction] = useState<'delete' | 'return'>('delete');
  const [adminPassword, setAdminPassword] = useState('');
  const [adminTransactionId, setAdminTransactionId] = useState('');
  const [paymentMethod, setPaymentMethod] = useState<'cash' | 'card' | 'split'>('card');
  const [cashAmount, setCashAmount] = useState('');
  const [cardAmount, setCardAmount] = useState('');
  const [splitCardAmount, setSplitCardAmount] = useState('');
  const [splitCashAmount, setSplitCashAmount] = useState('');

  // Calculate subtotal
  const subtotal = cartItems.reduce((total, item) => {
    const itemDiscount = item.discount || 0;
    const itemTotal = item.price * item.quantity;
    return total + (itemTotal * (1 - itemDiscount / 100));
  }, 0);

  // Calculate tax (20% VAT)
  const taxRate = 0.2;
  const taxAmount = subtotal * taxRate;

  // Calculate total
  const total = subtotal + taxAmount;

  // Calculate change for cash payment
  const calculateChange = () => {
    const cashReceived = parseFloat(cashAmount) || 0;
    return Math.max(0, cashReceived - total);
  };

  // Calculate remaining amount for split payment
  const calculateRemaining = () => {
    const cardPortion = parseFloat(splitCardAmount) || 0;
    return Math.max(0, total - cardPortion);
  };

  // Get transaction context functions
  const { addSaleTransaction } = useTransactions();
  
  // Get inventory context functions
  const { updateQuantityBySku } = useInventory();

  // Handle payment processing
  const handlePayment = () => {
    // Validate payment details
    if (paymentMethod === 'cash') {
      const cashReceived = parseFloat(cashAmount) || 0;
      if (cashReceived < total) {
        toast({
          title: "Insufficient payment",
          description: "Cash amount must be equal to or greater than the total.",
          variant: "destructive",
          duration: 3000,
        });
        return;
      }
    } else if (paymentMethod === 'split') {
      const cardPortion = parseFloat(splitCardAmount) || 0;
      const cashPortion = parseFloat(splitCashAmount) || 0;
      if (cardPortion + cashPortion < total) {
        toast({
          title: "Insufficient payment",
          description: "Total payment amount must equal the transaction total.",
          variant: "destructive",
          duration: 3000,
        });
        return;
      }
    }

    // Determine payment method description
    const paymentMethodDesc = paymentMethod === 'cash' 
      ? 'Cash'
      : paymentMethod === 'card'
        ? 'Card'
        : 'Split (Card/Cash)';

    // Create a sale transaction record
    const saleTransaction: SaleTransaction = {
      id: '', // Will be auto-generated by context
      type: 'sale',
      customerName: customer ? customer.name : 'Guest Customer',
      customerId: customer ? customer.id : undefined,
      items: cartItems.map(item => ({
        id: item.id,
        name: item.name,
        price: item.price,
        quantity: item.quantity,
        sku: item.sku,
        karat: item.karat,
        weight: item.weight,
        discount: item.discount
      })),
      totalAmount: total,
      date: new Date().toISOString().split('T')[0],
      paymentMethod: paymentMethodDesc
    };

    // Update inventory quantities for each item in the cart
    const inventoryUpdateResults = cartItems.map(item => {
      if (item.sku) {
        // Decrease inventory by the quantity purchased
        const success = updateQuantityBySku(item.sku, -item.quantity);
        return { sku: item.sku, name: item.name, success };
      }
      return { sku: item.sku || 'unknown', name: item.name, success: true };
    });
    
    // Check if any inventory updates failed
    const failedUpdates = inventoryUpdateResults.filter(result => !result.success);
    
    if (failedUpdates.length > 0) {
      // Some items couldn't be updated in inventory (likely insufficient stock)
      const failedItems = failedUpdates.map(item => item.name).join(', ');
      toast({
        title: "Inventory update warning",
        description: `The following items couldn't be updated in inventory (insufficient stock): ${failedItems}`,
        variant: "destructive",
        duration: 5000,
      });
    }
    
    // Add to transaction history
    addSaleTransaction(saleTransaction);

    // Payment description for toast
    const paymentDescription = paymentMethod === 'cash' 
      ? `Cash payment of ${formatCurrency(total)}`
      : paymentMethod === 'card'
        ? `Card payment of ${formatCurrency(total)}`
        : `Split payment: ${formatCurrency(parseFloat(splitCardAmount) || 0)} by card and ${formatCurrency(parseFloat(splitCashAmount) || 0)} in cash`;

    toast({
      title: "Payment successful",
      description: paymentDescription,
      duration: 3000,
    });
    
    setIsPaymentDialogOpen(false);
    onPaymentComplete();
  };

  // Get transaction context functions
  const { deleteTransaction, salesTransactions } = useTransactions();
  
  // Get auth context for admin password verification
  const { auth } = useAuth();

  // Handle admin action
  const handleAdminAction = () => {
    // Check if password is empty
    if (!adminPassword.trim()) {
      toast({
        title: "Missing password",
        description: "Please enter the admin password.",
        variant: "destructive",
        duration: 3000,
      });
      return;
    }
    
    // Verify password against the admin password from AuthContext
    if (adminPassword !== auth.password) {
      toast({
        title: "Authentication failed",
        description: "Incorrect admin password.",
        variant: "destructive",
        duration: 3000,
      });
      return;
    }
    
    // If action is return, show the return form
    if (adminAction === 'return') {
      setIsAdminDialogOpen(false);
      setIsReturnFormOpen(true);
      return;
    }

    if (adminAction === 'delete' && !adminTransactionId) {
      toast({
        title: "Missing information",
        description: "Please enter a transaction ID.",
        variant: "destructive",
        duration: 3000,
      });
      return;
    }

    // Process the admin action
    if (adminAction === 'delete' && adminTransactionId) {
      // Find the transaction before deleting it
      const transaction = salesTransactions.find(t => t.id === adminTransactionId);
      
      if (transaction && transaction.type === 'sale') {
        // Restore inventory quantities for each item in the deleted transaction
        transaction.items.forEach(item => {
          if (item.sku) {
            // Increase inventory by the quantity that was previously sold
            updateQuantityBySku(item.sku, item.quantity);
          }
        });
        
        toast({
          title: "Inventory restored",
          description: "Items have been returned to inventory.",
          duration: 3000,
        });
      }
      
      // Delete from transaction history
      deleteTransaction(adminTransactionId);
    }
    
    onAdminAction(adminAction, adminTransactionId);
    setIsAdminDialogOpen(false);
    setAdminPassword('');
    setAdminTransactionId('');

    toast({
      title: adminAction === 'delete' ? "Transaction deleted" : "Return processed",
      description: adminAction === 'delete' 
        ? `Transaction ${adminTransactionId} has been deleted.`
        : "Return has been processed successfully.",
      duration: 3000,
    });
  };

  // Format currency
  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-GB', {
      style: 'currency',
      currency: 'GBP'
    }).format(amount);
  };

  return (
    <div className="bg-gradient-to-br from-white/90 to-white/70 backdrop-blur-lg rounded-xl border border-gray-100 shadow-[0_2px_4px_rgba(0,0,0,0.05),inset_0_1px_1px_rgba(255,255,255,0.8)] hover:shadow-[0_4px_8px_rgba(0,0,0,0.1),inset_0_1px_2px_rgba(255,255,255,0.9)] transition-all duration-200 p-5 h-full flex flex-col">
      <h2 className="text-lg font-semibold mb-4 flex items-center text-gray-800">
        <CreditCard size={18} className="mr-2 text-gray-600" />
        Payment
      </h2>

      {/* Transaction Summary */}
      <div className="mb-6">
        <h3 className="text-sm font-medium mb-2">Transaction Summary</h3>
        <div className="bg-gray-50 rounded-md p-3">
          <div className="flex justify-between mb-2">
            <span className="text-sm">Subtotal:</span>
            <span className="text-sm">{formatCurrency(subtotal)}</span>
          </div>
          <div className="flex justify-between mb-2">
            <span className="text-sm">VAT (20%):</span>
            <span className="text-sm">{formatCurrency(taxAmount)}</span>
          </div>
          <div className="flex justify-between font-medium pt-2 border-t">
            <span>Total:</span>
            <span>{formatCurrency(total)}</span>
          </div>
        </div>
      </div>

      {/* Payment Actions */}
      <div className="space-y-3">
        <Dialog open={isPaymentDialogOpen} onOpenChange={setIsPaymentDialogOpen}>
          <DialogTrigger asChild>
            <Button 
              className="w-full bg-navy hover:bg-navy/90" 
              disabled={cartItems.length === 0}
            >
              Process Payment
            </Button>
          </DialogTrigger>
        <DialogContent className="sm:max-w-md">
          <DialogHeader>
            <DialogTitle>Payment</DialogTitle>
            <DialogDescription>
              Total amount: {formatCurrency(total)}
              {customer && (
                <span className="block mt-1">Customer: {customer.name}</span>
              )}
            </DialogDescription>
          </DialogHeader>
          
          <Tabs defaultValue="card" onValueChange={(value) => setPaymentMethod(value as any)}>
            <TabsList className="grid grid-cols-3 mb-4">
              <TabsTrigger value="card">Card</TabsTrigger>
              <TabsTrigger value="cash">Cash</TabsTrigger>
              <TabsTrigger value="split">Split</TabsTrigger>
            </TabsList>
            
            <TabsContent value="card" className="space-y-4">
              <div className="bg-gray-50 p-4 rounded-md text-center">
                <CreditCard size={36} className="mx-auto mb-2 text-navy" />
                <p className="font-medium">{formatCurrency(total)}</p>
                <p className="text-sm text-muted-foreground">Card payment</p>
              </div>
              <p className="text-sm text-muted-foreground">
                Process card payment using the card terminal.
              </p>
            </TabsContent>
            
            <TabsContent value="cash" className="space-y-4">
              <div className="grid gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="cash-amount">Cash received</Label>
                  <div className="relative">
                    <span className="absolute left-3 top-1/2 transform -translate-y-1/2">£</span>
                    <Input 
                      id="cash-amount" 
                      type="number"
                      min={total}
                      step="0.01"
                      className="pl-8"
                      value={cashAmount}
                      onChange={(e) => setCashAmount(e.target.value)}
                    />
                  </div>
                </div>
                
                <div className="bg-gray-50 p-4 rounded-md">
                  <div className="flex justify-between mb-2">
                    <span>Total:</span>
                    <span>{formatCurrency(total)}</span>
                  </div>
                  <div className="flex justify-between mb-2">
                    <span>Cash received:</span>
                    <span>{formatCurrency(parseFloat(cashAmount) || 0)}</span>
                  </div>
                  <div className="flex justify-between pt-2 border-t font-medium">
                    <span>Change due:</span>
                    <span>{formatCurrency(calculateChange())}</span>
                  </div>
                </div>
              </div>
            </TabsContent>
            
            <TabsContent value="split" className="space-y-4">
              <div className="grid gap-4">
                <div className="grid gap-2">
                  <Label htmlFor="card-portion">Card amount</Label>
                  <div className="relative">
                    <span className="absolute left-3 top-1/2 transform -translate-y-1/2">£</span>
                    <Input 
                      id="card-portion" 
                      type="number"
                      min="0"
                      max={total}
                      step="0.01"
                      className="pl-8"
                      value={splitCardAmount}
                      onChange={(e) => {
                        setSplitCardAmount(e.target.value);
                        const remaining = total - (parseFloat(e.target.value) || 0);
                        setSplitCashAmount(Math.max(0, remaining).toFixed(2));
                      }}
                    />
                  </div>
                </div>
                
                <div className="grid gap-2">
                  <Label htmlFor="cash-portion">Cash amount</Label>
                  <div className="relative">
                    <span className="absolute left-3 top-1/2 transform -translate-y-1/2">£</span>
                    <Input 
                      id="cash-portion" 
                      type="number"
                      min="0"
                      step="0.01"
                      className="pl-8"
                      value={splitCashAmount}
                      onChange={(e) => setSplitCashAmount(e.target.value)}
                    />
                  </div>
                </div>
                
                <div className="bg-gray-50 p-4 rounded-md">
                  <div className="flex justify-between mb-2">
                    <span>Total due:</span>
                    <span>{formatCurrency(total)}</span>
                  </div>
                  <div className="flex justify-between mb-2">
                    <span>Card payment:</span>
                    <span>{formatCurrency(parseFloat(splitCardAmount) || 0)}</span>
                  </div>
                  <div className="flex justify-between mb-2">
                    <span>Cash payment:</span>
                    <span>{formatCurrency(parseFloat(splitCashAmount) || 0)}</span>
                  </div>
                  <div className="flex justify-between pt-2 border-t font-medium">
                    <span>Remaining:</span>
                    <span>{formatCurrency(total - ((parseFloat(splitCardAmount) || 0) + (parseFloat(splitCashAmount) || 0)))}</span>
                  </div>
                </div>
              </div>
            </TabsContent>
          </Tabs>
          
          <DialogFooter className="flex flex-col sm:flex-row gap-2">
            <Button variant="outline" onClick={() => setIsPaymentDialogOpen(false)} className="sm:order-1">
              Cancel
            </Button>
            <Button onClick={handlePayment} className="sm:order-2 bg-navy hover:bg-navy/90">
              Complete Payment
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
      </div>

      {/* Admin Tools */}
      <div className="mt-4">
        <h3 className="text-sm font-medium mb-2 flex items-center">
          <AlertTriangle size={14} className="mr-1 text-amber-500" />
          Admin Tools
        </h3>
        
        <Dialog open={isAdminDialogOpen} onOpenChange={setIsAdminDialogOpen}>
          <div className="flex flex-col gap-2">
            <DialogTrigger asChild>
              <Button 
                variant="outline" 
                className="w-full text-sm py-1.5" 
                onClick={() => setAdminAction('return')}
              >
                <RefreshCw size={14} className="mr-2" />
                Return/Exchange
              </Button>
            </DialogTrigger>
            
            <DialogTrigger asChild>
              <Button 
                variant="outline" 
                className="w-full text-sm py-1.5 text-red-500 hover:text-red-600 hover:border-red-200" 
                onClick={() => setAdminAction('delete')}
              >
                <AlertTriangle size={14} className="mr-2" />
                Delete Transaction
              </Button>
            </DialogTrigger>
          </div>
          
          <DialogContent>
            <DialogHeader>
              <DialogTitle>
                {adminAction === 'delete' ? 'Delete Transaction' : 'Process Return/Exchange'}
              </DialogTitle>
              <DialogDescription>
                {adminAction === 'delete' 
                  ? 'This action requires admin approval and can only be performed within 24 hours of the transaction.'
                  : 'Process a return or exchange for a previous transaction.'}
              </DialogDescription>
            </DialogHeader>
            
            <div className="grid gap-4 py-4">
              {adminAction === 'delete' && (
                <div className="grid gap-2">
                  <Label htmlFor="transaction-id">Transaction ID</Label>
                  <Input 
                    id="transaction-id" 
                    value={adminTransactionId}
                    onChange={(e) => setAdminTransactionId(e.target.value)}
                    placeholder="Enter transaction ID"
                  />
                </div>
              )}
              
              <div className="grid gap-2">
                <Label htmlFor="admin-password">Admin Password</Label>
                <Input 
                  id="admin-password" 
                  type="password"
                  value={adminPassword}
                  onChange={(e) => setAdminPassword(e.target.value)}
                  placeholder="Enter admin password"
                  autoComplete="off"
                  className="focus:border-primary focus:ring-primary"
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      handleAdminAction();
                    }
                  }}
                />
              </div>
              
              <div className="bg-amber-50 p-3 rounded-md border border-amber-200 text-sm text-amber-800">
                <AlertTriangle size={14} className="inline-block mr-1" />
                {adminAction === 'delete'
                  ? 'Warning: This action permanently deletes the transaction record and cannot be undone.'
                  : 'Returns and exchanges will be logged and require proper documentation.'}
              </div>
            </div>
            
            <DialogFooter>
              <Button variant="outline" onClick={() => setIsAdminDialogOpen(false)}>
                Cancel
              </Button>
              <Button 
                onClick={handleAdminAction}
                variant={adminAction === 'delete' ? 'destructive' : 'default'}
              >
                {adminAction === 'delete' ? 'Delete Transaction' : 'Process Return'}
              </Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </div>
      
      {/* Return Form Dialog */}
      <ReturnForm 
        isOpen={isReturnFormOpen}
        onClose={() => setIsReturnFormOpen(false)}
        onSuccess={() => {
          setIsReturnFormOpen(false);
          toast({
            title: "Return processed",
            description: "Return has been processed successfully and inventory updated.",
            duration: 3000,
          });
          onAdminAction('return');
        }}
      />
    </div>
  );
};

export default PaymentPanel;
