import {
  Controller,
  Get,
  Post,
  Patch,
  Body,
  Param,
  Query,
  UseGuards,
  HttpCode,
  HttpStatus,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBearerAuth,
  ApiQuery,
} from '@nestjs/swagger';
import { ThrottlerGuard } from '@nestjs/throttler';
import { FinancialIntelligenceService } from './financial-intelligence.service';
import { JwtAuthGuard } from '../../shared/guards/jwt-auth.guard';
import { TenantGuard } from '../../shared/guards/tenant.guard';
import { CurrentUser } from '../../shared/decorators/user.decorator';
import { TenantId } from '../../shared/decorators/tenant.decorator';
import {
  GenerateAnalysisDto,
  FinancialAnalysisResponseDto,
  RecommendationResponseDto,
  UpdateRecommendationDto,
  DashboardSummaryDto,
} from './dto/financial-intelligence.dto';

@ApiTags('Financial Intelligence')
@Controller('financial-intelligence')
@UseGuards(ThrottlerGuard, JwtAuthGuard, TenantGuard)
@ApiBearerAuth('access-token')
export class FinancialIntelligenceController {
  constructor(
    private readonly financialIntelligenceService: FinancialIntelligenceService,
  ) {}

  @Post('analyses')
  @ApiOperation({
    summary: 'Generate financial analysis with AI insights',
    description:
      'Analyzes financial data for specified period and generates AI-powered insights and recommendations',
  })
  @ApiResponse({
    status: 201,
    description: 'Analysis generated successfully',
    type: FinancialAnalysisResponseDto,
  })
  @ApiResponse({
    status: 400,
    description: 'Invalid request parameters',
  })
  async generateAnalysis(
    @Body() dto: GenerateAnalysisDto,
    @TenantId() tenantId: string,
    @CurrentUser('id') userId: string,
  ): Promise<FinancialAnalysisResponseDto> {
    return this.financialIntelligenceService.generateAnalysis(
      dto,
      tenantId,
      userId,
    );
  }

  @Get('dashboard')
  @ApiOperation({
    summary: 'Get dashboard summary',
    description:
      'Retrieves key metrics, trends, and recent recommendations for dashboard display',
  })
  @ApiResponse({
    status: 200,
    description: 'Dashboard summary retrieved successfully',
    type: DashboardSummaryDto,
  })
  async getDashboard(
    @TenantId() tenantId: string,
  ): Promise<DashboardSummaryDto> {
    return this.financialIntelligenceService.getDashboardSummary(tenantId);
  }

  @Get('analyses')
  @ApiOperation({
    summary: 'Get list of financial analyses',
    description:
      'Retrieves historical financial analyses with optional filtering',
  })
  @ApiQuery({ name: 'analysisType', required: false })
  @ApiQuery({ name: 'limit', required: false, type: Number })
  @ApiResponse({
    status: 200,
    description: 'Analyses retrieved successfully',
    type: [FinancialAnalysisResponseDto],
  })
  async getAnalyses(
    @TenantId() tenantId: string,
    @Query('analysisType') analysisType?: string,
    @Query('limit') limit?: string,
  ): Promise<FinancialAnalysisResponseDto[]> {
    return this.financialIntelligenceService.getAnalyses(tenantId, {
      analysisType,
      limit: limit ? parseInt(limit) : undefined,
    });
  }

  @Get('analyses/:id')
  @ApiOperation({
    summary: 'Get specific analysis by ID',
    description: 'Retrieves detailed financial analysis including AI insights',
  })
  @ApiResponse({
    status: 200,
    description: 'Analysis retrieved successfully',
    type: FinancialAnalysisResponseDto,
  })
  @ApiResponse({
    status: 404,
    description: 'Analysis not found',
  })
  async getAnalysisById(
    @Param('id') id: string,
    @TenantId() tenantId: string,
  ): Promise<FinancialAnalysisResponseDto> {
    return this.financialIntelligenceService.getAnalysisById(id, tenantId);
  }

  @Get('recommendations')
  @ApiOperation({
    summary: 'Get AI recommendations',
    description:
      'Retrieves business recommendations generated by AI with filtering options',
  })
  @ApiQuery({ name: 'status', required: false })
  @ApiQuery({ name: 'category', required: false })
  @ApiQuery({ name: 'priority', required: false })
  @ApiQuery({ name: 'limit', required: false, type: Number })
  @ApiResponse({
    status: 200,
    description: 'Recommendations retrieved successfully',
    type: [RecommendationResponseDto],
  })
  async getRecommendations(
    @TenantId() tenantId: string,
    @Query('status') status?: string,
    @Query('category') category?: string,
    @Query('priority') priority?: string,
    @Query('limit') limit?: string,
  ): Promise<RecommendationResponseDto[]> {
    return this.financialIntelligenceService.getRecommendations(tenantId, {
      status,
      category,
      priority,
      limit: limit ? parseInt(limit) : undefined,
    });
  }

  @Patch('recommendations/:id')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({
    summary: 'Update recommendation status',
    description:
      'Updates recommendation status (e.g., mark as implemented, dismissed)',
  })
  @ApiResponse({
    status: 200,
    description: 'Recommendation updated successfully',
    type: RecommendationResponseDto,
  })
  @ApiResponse({
    status: 404,
    description: 'Recommendation not found',
  })
  async updateRecommendation(
    @Param('id') id: string,
    @Body() dto: UpdateRecommendationDto,
    @TenantId() tenantId: string,
    @CurrentUser('id') userId: string,
  ): Promise<RecommendationResponseDto> {
    return this.financialIntelligenceService.updateRecommendation(
      id,
      dto,
      tenantId,
      userId,
    );
  }
}
