-- Create customers table if it doesn't exist
CREATE TABLE IF NOT EXISTS `customers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NULL,
  `phone_primary` VARCHAR(50) NOT NULL,
  `phone_secondary` VARCHAR(50) NULL,
  `address_line1` VARCHAR(255) NULL,
  `address_line2` VARCHAR(255) NULL,
  `city` VARCHAR(100) NULL,
  `state` VARCHAR(100) NULL,
  `postal_code` VARCHAR(20) NULL,
  `country` VARCHAR(100) NULL DEFAULT 'India',
  `profile_image_path` VARCHAR(255) NULL,
  `drive_profile_image_id` VARCHAR(100) NULL,
  `notes` TEXT NULL,
  `marketing_email` BOOLEAN NOT NULL DEFAULT 0,
  `marketing_sms` BOOLEAN NOT NULL DEFAULT 0,
  `marketing_phone` BOOLEAN NOT NULL DEFAULT 0,
  `data_processing_consent` BOOLEAN NOT NULL DEFAULT 0,
  `created_by` INT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idx_customer_name` (`first_name`, `last_name`),
  INDEX `idx_customer_email` (`email`),
  INDEX `idx_customer_phone` (`phone_primary`),
  CONSTRAINT `fk_customer_created_by` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
